Added an argument for parallelism in flink_execute_sql
getindata/streaming-jupyter-integrations pull request #59
Opened 2022-11-15 14:44 UTC by andrzejdackiewicz

2022-11-15 14:53 UTC, grzegorz8 requested changes

2022-11-15 14:53 UTC, grzegorz8 commented on CHANGELOG.md
> +-   Parallelism argument for flink_execute_sql.
No need to duplicate `Added` section. Please add it just below `Support Java 8`

2022-11-15 14:53 UTC, grzegorz8 commented on streaming_jupyter_integrations/magics.py
> +        parallelism = args.parallelism
let's make it shorter:
```self.s_env.set_parallelism(args.parallelism)```

2022-11-15 14:56 UTC, andrzejdackiewicz commented on streaming_jupyter_integrations/magics.py
> +        parallelism = args.parallelism
Done

2022-11-15 15:02 UTC, grzegorz8 commented on streaming_jupyter_integrations/magics.py
> +            get_gateway().jvm.org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.createLocalEnvironmentWithWebUI(
revert

2022-11-15 15:09 UTC, andrzejdackiewicz commented on streaming_jupyter_integrations/magics.py
> +            get_gateway().jvm.org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.createLocalEnvironmentWithWebUI(
Done!

2022-11-16 12:42 UTC, grzegorz8 approved these changes

2022-11-21 13:27 UTC, niladrem commented on streaming_jupyter_integrations/magics.py
> +    @argument("--parallelism", "-par", type=int, help="Flink parallelism to use when running the SQL", required=False,
please change the short flag to `-p`

2022-11-22 07:35 UTC, niladrem approved these changes

2022-11-22 07:35 UTC, merged